# Generated by Django 3.1.3 on 2020-12-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201206_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='SD card'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_max_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SD max volume'),
        ),
    ]
