# Generated by Django 3.1.4 on 2020-12-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201214_2104'),
        ('main', '0003_auto_20201214_2052'),
    ]

    operations = [
    ]
